from prompts.manim_prompt import MANIM_SYSTEM_PROMPT, MANIM_USER_TEMPLATE
from prompts.narration_prompt import NARRATION_SYSTEM_PROMPT, NARRATION_USER_TEMPLATE
from prompts.planner_prompt import VISUAL_PLANNER_SYSTEM_PROMPT, VISUAL_PLANNER_USER_TEMPLATE
from prompts.remotion_prompt import REMOTION_SYSTEM_PROMPT, REMOTION_USER_TEMPLATE
from prompts.router_prompt import ROUTER_PROMPT

__all__ = [
    "ROUTER_PROMPT",
    "VISUAL_PLANNER_SYSTEM_PROMPT",
    "VISUAL_PLANNER_USER_TEMPLATE",
    "NARRATION_SYSTEM_PROMPT",
    "NARRATION_USER_TEMPLATE",
    "MANIM_SYSTEM_PROMPT",
    "MANIM_USER_TEMPLATE",
    "REMOTION_SYSTEM_PROMPT",
    "REMOTION_USER_TEMPLATE",
]
